### ISSUE TITLE
Readme doesn't explain how it is used

### ISSUE THREAD

**Issue by odinho** [allaboutapps/integresql#1]
Sure you can run it, which the readme writes a lot about, but what does it actually do?

The why could also be explained more thoroughly. Why would you want to use this, which problems does it solve? 

Thanks a lot!

**Comment by majodev** [comment]
Hi,

you are absolutely right about that. We'll try to explain the concept and setup in detail in the following days. 

Thanks for reporting.

**Comment by majodev** [comment]
I've finally had time to create the [Background](https://github.com/allaboutapps/integresql#background) section in the README. Feel free to open other another issue if some aspect is left in the dark.
