### ISSUE TITLE
The database returned by `GetTestDatabase` is dirty if a test has already been run.

### ISSUE THREAD

**Issue by kvhc308** [allaboutapps/integresql#13]
I'm running integresql and pg via docker compose. I've initialized my db template and run migrations, all good so far.

Now that I have a template hash, I run my unit test (simple insert)

- GetTestDatabase
- Insert single entry in one of the tables
- ReturnTestDatabase

Now when I run the same test again, the database is not clean. Its seems the database is not properly destroyed when returned?
Am I supposed to use transactions to keep the databases clean? Or manually truncate tables.
Any help would be appreciated.

**Comment by kvhc308** [comment]
Duplicate of #2

**Comment by bimusiek** [comment]
I have also stumbled across the same problem. I was expecting the database to be cleaned and then send back to the pool. 
No problem doing this by ourselves, however the documentation was misleading.

**Comment by majodev** [comment]
Closed via https://github.com/allaboutapps/integresql/pull/16
