### ISSUE TITLE
Support arm64 CPU architecture for Apple Silicon (M1) compatibility

### ISSUE THREAD

**Issue by schuerg** [allaboutapps/integresql#15]
First of all, thank you for this great piece of software. Our tests have witnessed a significant boost in speed, surpassing all expectations by orders of magnitude!

But currently, IntegreSQL does not have builds the arm64 CPU architecture, which prevents it from running on Apple Silicon (M1) machines. To make IntegreSQL more inclusive and compatible with a wider range of hardware, we should add support for the arm64 architecture.

A Go build for arm54 and Apple M1 can be done with:

```shell
GOOS=darwin GOARCH=arm64 go build
```

- Supporting arm64 architecture is important to ensure our project is accessible to a broader user base, especially those with Apple Silicon (M1) devices.
- Building a Docker container image that can target multiple platforms, including arm64, would also enhance the versatility of IntegreSQL. Docker's multi-platform build documentation can be found here: [Docker Multi-platform Build](https://docs.docker.com/build/building/multi-platform/).

**Comment by bartoszhernas** [comment]
Seconded. We use IntegreSQL locally and all our devs work from M1 macs. That would benefit all macOS devs a lot.

**Comment by majodev** [comment]
Closed via https://github.com/allaboutapps/integresql/pull/16
