### ISSUE TITLE
Help setting up IntegreSQL

### ISSUE THREAD

**Issue by bar-ailo** [allaboutapps/integresql#5]
Hey guys, this isn't actually an issue with IntegreSQL - i'm trying to demo IntegreSQL to replace our test DB provider in a Java project, to start out i'm using the docker-compose template and trying to interact with it using Postman.
Trying to send `POST 127.0.0.1:5000/templates` with -
`{"hash": "some_string"}` in the body is receiving a 404 not found response.
I'm not sure what I could be doing wrong at this step, I thought this was the initial interaction with IntegreSQL so I can't imagine what resource it's looking for.

Sorry for using this medium to contact you,
I wasn't sure how else to do so.
Thanks in advance

**Comment by majodev** [comment]
Hi @bar-ailo!

Oh, it seems we forgot to document the path prefixes properly, see [templates router](https://github.com/allaboutapps/integresql/blob/master/internal/api/templates/routes.go) und [admin router](https://github.com/allaboutapps/integresql/blob/master/internal/api/admin/routes.go).

Please prepend `/api/v1/templates` to all calls except deleting all templates (which is `/api/v1/admin`). e.g.:
* `POST /api/v1/templates`: initialize template
* `PUT api/v1/templates/{hash}`: finalize template
* `DELETE /api/v1/templates/{hash}`: discard a template
* `GET /api/v1/templates/{hash}/tests`: get test database
* `DELETE /api/v1/templates/{hash}/{id}`: return test database
* `DELETE /api/v1/admin/templates`: delete all templates

Our current go client implementation should give you an overview on how we integrate with the server: [integresql-client-go client.go](https://github.com/allaboutapps/integresql-client-go/blob/master/client.go)

Sorry for the inconvenience.

**Comment by majodev** [comment]
Closed via https://github.com/allaboutapps/integresql/pull/16
