### ISSUE TITLE
404 for readme "install locally" URL

### ISSUE THREAD

**Issue by ksamuel** [allaboutapps/integresql#7]
README says to do:

```bash
go get github.com/allaboutapps/integresql/cmd/server
```

But:

```bash
$ http github.com/allaboutapps/integresql/cmd/server --check-status --follow
HTTP/1.1 404 Not Found
```

`github.com/allaboutapps/integresql/tree/master/cmd/server` does exist but:

```bash
$ go get -v github.com/allaboutapps/integresql/blob/master/cmd/server/  
github.com/allaboutapps/integresql (download)
package github.com/allaboutapps/integresql/blob/master/cmd/server: cannot find package "github.com/allaboutapps/integresql/blob/master/cmd/server" in any of:
	/usr/lib/go-1.13/src/github.com/allaboutapps/integresql/blob/master/cmd/server (from $GOROOT)
	/home/user/go/src/github.com/allaboutapps/integresql/blob/master/cmd/server (from $GOPATH) ```

**Comment by majodev** [comment]
Hi,

this might be related to [Go modules @v1.13](https://maelvls.dev/go111module-everywhere/#go111module-with-go-113), anything >v1.14 should be fine, just tried the following inside a [golang:1.16.3](https://hub.docker.com/_/golang) container:
```bash
$ go get github.com/allaboutapps/integresql/cmd/server
go: downloading github.com/allaboutapps/integresql v1.0.0
go get: added github.com/allaboutapps/integresql v1.0.0
$ go install github.com/allaboutapps/integresql/cmd/server # installs as `server` executable
```

We only use the [allaboutapps/integresql](https://hub.docker.com/r/allaboutapps/integresql) docker image currently within [allaboutapps/go-starter](https://github.com/allaboutapps/go-starter), so there might still be issues when installing IntegreSQL locally that we are unaware of yet.

**Comment by ksamuel** [comment]
As I said, github.com/allaboutapps/integresql/cmd/server is a 404 for me. It's not related to go.

![image](https://user-images.githubusercontent.com/221886/116384216-edaa3080-a817-11eb-9d45-7f4628fc7a49.png)

**Comment by majodev** [comment]
Closed via https://github.com/allaboutapps/integresql/pull/16
